# Generated by Django 3.2 on 2021-05-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cuisine',
            new_name='cuisine_raw',
        ),
    ]
