# Generated by Django 3.2 on 2021-05-03 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_cuisine_recipe_cuisine_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title1', models.CharField(max_length=50)),
                ('title2', models.CharField(max_length=50)),
                ('title3', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('title1', 'title2', 'title3')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.cuisine'),
        ),
    ]
